DidactischeLeermiddelen/Models/Domain/Reservatie.cs
using System;
using System.Collections.Generic;
using DidactischeLeermiddelen.Models.Domain.StateMachine;
using DidactischeLeermiddelen.ViewModels;

namespace DidactischeLeermiddelen.Models.Domain
{
    public abstract class Reservatie :IComparable<Reservatie>
    {
        private ReservatieState _reservatieState;
        public int ReservatieId { get; set; }
        public virtual Materiaal Materiaal { get; set; }
        public virtual Gebruiker Gebruiker { get; set; }
        public virtual IList<Dag> GeblokkeerdeDagen { get; set; } 
        public int AantalGereserveerd { get; set; }
        public int AantalUitgeleend { get; set; }
        public int AantalTerugGebracht { get; set; }
        public DateTime StartDatum { get; set; }
        public DateTime EindDatum { get; set; }
        public DateTime AanmaakDatum { get; set; }
        public ReservatieStateEnum ReservatieStateEnum { get; set; }
        public ReservatieState ReservatieState
        {
            get
            {
                switch (ReservatieStateEnum)
                {
                    case ReservatieStateEnum.Geblokkeerd: return new Geblokkeerd(this);
                    case ReservatieStateEnum.Gereserveerd: return new Gereserveerd(this);
                    case ReservatieStateEnum.Opgehaald: return new Opgehaald(this);
                    case ReservatieStateEnum.TeLaat: return new TeLaat(this);
                    case ReservatieStateEnum.Overruled: return new Overruled(this);
                }
                return null;
            }
            set
            {
                _reservatieState = value;
                switch (_reservatieState.GetType().Name)
                {
                    case "Geblokkeerd": ReservatieStateEnum = ReservatieStateEnum.Geblokkeerd; break;
                    case "Gereserveerd": ReservatieStateEnum = ReservatieStateEnum.Gereserveerd; break;
                    case "TeLaat": ReservatieStateEnum = ReservatieStateEnum.TeLaat; break;
                    case "Opgehaald": ReservatieStateEnum = ReservatieStateEnum.Opgehaald; break;
                    case "Overruled":
                        ReservatieStateEnum = ReservatieStateEnum.Overruled;
                        break;

                }
            }
        }

        public Reservatie()
        {
            GeblokkeerdeDagen = new List<Dag>();
            AanmaakDatum = DateTime.Now;
        }

        public Reservatie(Gebruiker gebruiker, Materiaal materiaal, string startDatum, int aantal)
        {
            if (materiaal == null)
                throw new ArgumentNullException("U heeft nog geen items geselecteerd voor deze reservatie");

            if (gebruiker is Student)
            {
                var week = HulpMethode.GetIso8601WeekOfYear(Convert.ToDateTime(startDatum));
                StartDatum = HulpMethode.FirstDateOfWeekISO8601(DateTime.Now.Year, week);
                EindDatum = StartDatum.AddDays(4);
            }

            if (gebruiker is Lector)
            {
                StartDatum = Convert.ToDateTime(startDatum);
                EindDatum = Convert.ToDateTime(HulpMethode.GetEindDatum(startDatum));
            }

            Materiaal = materiaal;
            AantalGereserveerd = aantal;
            Gebruiker = gebruiker;
            GeblokkeerdeDagen = new List<Dag>();
            AanmaakDatum = DateTime.Now;
        }

        public bool KanOverschrijvenMetReservatie(DateTime startdatum, DateTime eindDatum)
        {
            return startdatum <= EindDatum && eindDatum >= StartDatum;
        }

        public void Blokkeer()
        {
            ReservatieState.Blokkeer();
        }

        public void Overruul()
        {
            ReservatieState.Overruul();
        }

        public void ToState(ReservatieState reservatieState)
        {
            ReservatieState = reservatieState;
            ReservatieState.Reservatie = this;
        }


        public int CompareTo(Reservatie other)
        {
            if (this.Gebruiker is Lector)
                return 1;
            if (this.Gebruiker is Student && other.Gebruiker is Student)
                return 0;
            return -1;
        }
    }
}

DidactischeLeermiddelen/ViewModels/ReservatieViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using DidactischeLeermiddelen.Models.Domain;

namespace DidactischeLeermiddelen.ViewModels
{
    public class ReservatieViewModel : IViewModel
    {
        public string Foto { get; set; }
        public string Naam { get; set; }
        public string Firma { get; set; }
        public int MateriaalId { get; set; }
        public string Omschrijving { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime StartDatum { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime EindDatum { get; set; }
        public int AantalStuksGereserveerd { get; set; }
        public string Status { get; set; }
        public long ReservatieId { get; set; }

        public ReservatieViewModel(Reservatie reservatie)
        {
            Foto = reservatie.Materiaal.ImageSrc;
            Naam = reservatie.Materiaal.Naam;
            Firma = reservatie.Materiaal.Firma?.Naam;
            Omschrijving = reservatie.Materiaal.Omschrijving;
            MateriaalId = reservatie.Materiaal.MateriaalId;
            StartDatum = reservatie.StartDatum;
            EindDatum = StartDatum.AddDays(4);
            AantalStuksGereserveerd = reservatie.AantalGereserveerd;
            Status = reservatie.StartDatum <= DateTime.Now.AddDays(7) ? reservatie.ReservatieState.GetType().Name : "Geen status";
            ReservatieId = reservatie.ReservatieId;
        }
    }

    public class ReservatieMaterialenViewModel : IViewModel
    {
        public IEnumerable<ReservatieViewModel> Materialen { get; set; }
    }
}

DidactischeLeermiddelen/Controllers/ReservatieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DidactischeLeermiddelen.Models.Domain;
using DidactischeLeermiddelen.Models.Domain.InterfaceRepositories;
using DidactischeLeermiddelen.Models.Domain.Mail;
using DidactischeLeermiddelen.Models.Domain.StateMachine;
using DidactischeLeermiddelen.ViewModels;

namespace DidactischeLeermiddelen.Controllers
{
    [Authorize]
    public class ReservatieController : Controller
    {
        // GET: Reservatie
        private IMateriaalRepository materiaalRepository;
        private IGebruikerRepository gebruikerRepository;
        private IReservatieRepository reservatieRepository;
        private IMailServiceRepository mailServiceRepository;

        public ReservatieController(IMateriaalRepository materiaalRepository, IGebruikerRepository gebruikerRepository, IReservatieRepository reservatieRepository, IMailServiceRepository mailServiceRepository)
        {
            this.materiaalRepository = materiaalRepository;
            this.gebruikerRepository = gebruikerRepository;
            this.reservatieRepository = reservatieRepository;
            this.mailServiceRepository = mailServiceRepository;
        }

        public ActionResult Index(Gebruiker gebruiker)
        {
            if (gebruiker.Reservaties.Count == 0)
                return View("LegeReservatielijst");

            ICollection<Reservatie> reservatielijst = gebruiker.Reservaties;

            //IList<Materiaal> materiaallijst = VulMateriaalLijstIn(reservatielijst); 

            ViewBag.Gebruikersnaam = gebruiker.Naam;
            ViewBag.AantalReservaties = reservatielijst.Count();

            ReservatieMaterialenViewModelFactory rvmf = new ReservatieMaterialenViewModelFactory();
            ReservatieMaterialenViewModel vm = rvmf.CreateReservatieMaterialenViewModel(gebruiker) as ReservatieMaterialenViewModel;

            return View(vm);
        }

        public ActionResult MaakReservatie()
        {
            return View("Index");
        }

        [HttpPost]
        public void MaakReservatie(Gebruiker gebruiker, int[] materiaal, int[] aantal, string startDatum, string[] dagen)
        {
            IList<Materiaal> materialen = GeefMaterialenVanId(materiaal);

            string eersteDag = HulpMethode.GetStartDatum(startDatum).ToShortDateString();

            if (materialen.Count > 0)
            {
                IDictionary<Materiaal, int> potentieleReservaties = InvullenVanMapMetPotentieleReservaties(aantal, materialen);

                try
                {
                    if (gebruiker is Student)
                        {
                            Student student = gebruiker as Student;

                        student.MaakReservaties(potentieleReservaties, eersteDag);
                        VerstuurMailStudent(potentieleReservaties, eersteDag, student);

                        TempData["Info"] = $"Reservatie werd aangemaakt";
                    }
                    else
                    {
                        Lector lector = gebruiker as Lector;

                        lector.MaakBlokkeringen(potentieleReservaties, eersteDag,dagen);

                        VerstuurMailBlokkeringLector(potentieleReservaties, dagen, lector);
                        IList<Reservatie> overruled = lector.OverruledeReservaties;
                        VerstuurMailNaarStudentDieOverruledIs(overruled);

                        TempData["Info"] = $"Reservatie werd aangemaakt";
                    }

                    gebruikerRepository.SaveChanges();
                }
                catch (ArgumentException ex)
                {
                    TempData["Error"] = ex.Message;
                }
            }
        }

        private void VerstuurMailNaarStudentDieOverruledIs(IList<Reservatie> overruledeReservaties )
        {
            
            foreach (var reservatie in overruledeReservaties)
            {
                VerstuurMailBlokkeringStudent(reservatie.Materiaal, reservatie.StartDatum.ToShortDateString(), reservatie.Gebruiker);
            }
        }

        [HttpPost]
        public ActionResult VerwijderReservatie(int id, Gebruiker gebruiker)
        {
            Reservatie r = reservatieRepository.FindById(id);
            try
            {
                gebruiker.VerwijderReservatie(r);
                reservatieRepository.Remove(r);
                reservatieRepository.SaveChanges();
                gebruikerRepository.SaveChanges();
                
                TempData["Info"] = "Reservatie is succesvol verwijderd";
            }
            catch (ArgumentException ex)
            {
                TempData["Error"] = ex.Message;
            }

            return RedirectToAction("Index");
        }

        private IList<Materiaal> GeefMaterialenVanId(int[] materiaal)
        {
            return materiaal.Select(id => materiaalRepository.FindAll().FirstOrDefault(m => m.MateriaalId == id)).ToList();
        }

        private IDictionary<Materiaal, int> InvullenVanMapMetPotentieleReservaties(int[] aantal, IList<Materiaal> materialen)
        {
            IDictionary<Materiaal, int> potentieleReservaties = new Dictionary<Materiaal, int>();

            for (int index = 0; index < materialen.Count; index++)
            {
                potentieleReservaties.Add(materialen[index], aantal[index]);
            }

            return potentieleReservaties;
        }

        private void VerstuurMailStudent(IDictionary<Materiaal, int> potentieleReservaties, string startDatum, Gebruiker gebruiker)
        {
            MailTemplate mail = mailServiceRepository.GeefMailTemplate("Bevestiging reservatie");
            mail.MaakMail(potentieleReservaties, null, startDatum, HulpMethode.GetEindDatum(startDatum).ToShortDateString(), null, gebruiker);
        }

        private void VerstuurMailBlokkeringLector(IDictionary<Materiaal, int> blokkeringen, string[] dagen,
            Gebruiker gebruiker)
        {
            MailTemplate mail = mailServiceRepository.GeefMailTemplate("Blokkering");
            mail.MaakMail(blokkeringen, null, "", "", dagen, gebruiker);
        }

        private void VerstuurMailBlokkeringStudent(Materiaal materiaal, string startDatum,
            Gebruiker gebruiker)
        {
            MailTemplate mail = mailServiceRepository.GeefMailTemplate("Reservatie gewijzigd");
            mail.MaakMail(null, materiaal, startDatum, "", null, gebruiker);
        }     

        //private IList<Materiaal> VulMateriaalLijstIn(ICollection<Reservatie> reservatielijst)
        //{
        //    IList<Materiaal> materiaallijst = new List<Materiaal>();

        //    foreach (Materiaal materiaal in reservatielijst.Select(r => r.Materiaal))
        //    {
        //        materiaallijst.Add(materiaal);
        //    }

        //    return materiaallijst;
        //}
    }
}

DidactischeLeermiddelen/Views/Reservatie/Index.cshtml
@using DidactischeLeermiddelen.Models.Domain
@model DidactischeLeermiddelen.ViewModels.ReservatieMaterialenViewModel

@{
    ViewBag.Title = User.IsInRole("Lector") ? "Blokkeringen" : "Reservaties";
}


<h2>Mijn @(User.IsInRole("Lector") ? "blokkeringen" : "reservaties")</h2>
<h4>@ViewBag.Gebruikersnaam</h4>
<h5>Aantal @(User.IsInRole("Lector") ? "blokkeringen" : "reservaties"): @ViewBag.AantalReservaties</h5>

@foreach (var item in Model.Materialen)
{
    <div class="row materiaal">
    <div class="materiaal-content">
        <div class="img-side">
            <div class="col-md-2 col-sm-2 col-xs-12 img-tag">
                <a href="@item.Foto" data-lightbox="@item.MateriaalId" data-title="@item.Naam">
                    <img src="@item.Foto" alt="@item.Foto" itemprop="@item.MateriaalId">
                </a>
            </div>
        </div>
        <div class="info-side">
 
                <div class="hidden-lg hidden-md hidden-sm col-xs-12 text-center">
                    <h4 class="">@Html.DisplayFor(modelItem => item.Naam)</h4>
                </div>
      
                <div class="col-md-2 col-sm-10 hidden-xs">
                    <h4 class="">@Html.DisplayFor(modelItem => item.Naam)</h4>
                </div>
            <div class="col-md-2 col-sm-2 col-xs-6">
                <div class="startdatum">
                    <h4>Startdatum</h4>
                    <h5>@Html.DisplayFor(modelItem => item.StartDatum)</h5>
                </div>

            </div>
            <div class="col-md-2 col-sm-2 col-xs-6">
                <div class="einddatum">
                    <h4>Einddatum</h4>
                    <h5>@Html.DisplayFor(modelItem => item.EindDatum)</h5>
                </div>

            </div>
            <div class="col-md-1 col-sm-2 col-xs-6">
                <div class="aantal">
                    <h4>Aantal</h4>
                    <h5>@Html.DisplayFor(modelItem => item.AantalStuksGereserveerd)</h5>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-6">
                <div class="aantal">
                    <h4>Status</h4>
                    <h5>@Html.DisplayFor(modelItem => item.Status)</h5>
                </div>
            </div>
            <div class="row">
                <div class="col-md-1 col-sm-2 hidden-xs">
                    @using (Html.BeginForm("VerwijderReservatie", "Reservatie", new { id = item.ReservatieId })) // hier nog reservatieId nemen
                    {

                        <button type="submit" class="btn btn-delete" id="reservatie-delete">
                            <span class="glyphicon glyphicon-remove"></span>
                        </button>
                    }


                </div>
            </div>
            <div class="row text-center">
                <div class="hidden-lg hidden-md hidden-sm col-xs-12">
                    @using (Html.BeginForm("VerwijderReservatie", "Reservatie", new { id = item.MateriaalId })) // hier nog reservatieId nemen
                    {

                        <button type="submit" class="btn btn-delete">
                            <span class="glyphicon glyphicon-remove"></span> Verwijderen
                        </button>
                    }


                </div>
            </div>
        </div>
    </div>
        </div>
}

DidactischeLeermiddelen/Views/Reservatie/LegeReservatieLijst.cshtml
@using DidactischeLeermiddelen.Models.Domain
@{
    ViewBag.Title = User.IsInRole("Lector") ? "Blokkeringen" : "Reservaties";
}
<div>
    <h2>U heeft momenteel geen @(User.IsInRole("Lector") ? "blokkeringen" : "reservaties")</h2>
    <p>@Html.ActionLink("Reservaties maken?", "Index", "Verlanglijst")</p>
</div>